---
title: "STATS_107_HalfwayProj 2025-11-02"
author: "Jessica Xia"
date: "2025-10-24"
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

-   Describe data source(s) and variables\
-   Cleaning steps and missing data handling\
-   Sample sizes and variable types\
-   Any transformations or merges

```{r reset env}
rm(list = ls())
```

```{r datasets}
#events in US from 1980 - 2024
events_data <- read.csv("data/events-US-1980-2024-Q4.csv")
events_data <- na.omit(events_data)
events_data <- events_data[-c(1, 2), ]

#insurance data
insurance_data <- read.csv("data/all_insurance_costs.csv")
insurance_data <- na.omit(insurance_data)

#property insurance cost data
prop_insurance <- read.csv("data/property_insurance_costs.csv")
prop_insurance <- na.omit(prop_insurance)
```

```{r}
colnames(events_data) <- c("Name_Date", #chr
                           "Disaster_Type", #chr
                           "Begin_Date", #num -> chr (date format)
                           "End_Date", #num -> chr (date format)
                          "CPI_Adjusted_Cost_Millions", #num
                          "Unadjusted_Cost_Millions", #num
                          "Deaths") #int

events_data$CPI_Adjusted_Cost_Millions <- as.numeric(events_data$CPI_Adjusted_Cost_Millions)
events_data$Unadjusted_Cost_Millions <- as.numeric(events_data$Unadjusted_Cost_Millions)
events_data$Deaths <- as.integer(events_data$Deaths)


events_data$Begin_Date <- as.Date(as.character(events_data$Begin_Date),
                          format = "%Y%m%d")

events_data$End_Date <- as.Date(as.character(events_data$End_Date), 
                        format = "%Y%m%d")

events_data$CPI_Adjusted_Cost_Millions <- as.numeric(events_data$CPI_Adjusted_Cost_Millions)

events_data$Unadjusted_Cost_Millions <- as.numeric(events_data$Unadjusted_Cost_Millions)

events_data$Deaths <- as.numeric(events_data$Deaths)

head(events_data)
dim(events_data)
```

```{r}
colnames(insurance_data) <- c("PPI_Series_ID", 
                              "Year", 
                              "Month_Code", 
                              "Time_Period", 
                              "All_Insurance_Index")

head(insurance_data)
```

```{r}
colnames(prop_insurance) <- c("Series_ID", 
                  "Year", 
                  "Month_Code", 
                  "Time_Period", 
                  "Property_Insurance_Index")

head(prop_insurance)

#our property insurance contains data that the overall insurance does not have (2009 march-2009 may), so we will remove it to have thedata match 1-1

prop_insurance <- prop_insurance[-c(1:3),]

save.image("12_cleanedData.RData")
```
